services:
  # Nginx Proxy Manager (вместо старого самодельного Nginx)
  npm:
    image: 'jc21/nginx-proxy-manager:latest'
    container_name: nginx_proxy_manager
    restart: unless-stopped
    ports:
      - "80:80"   # Публичный HTTP-порт
      - "443:443" # Публичный HTTPS-порт
      - "81:81"   # Админ-панель NPM (http://IP_сервера:81)
    volumes:
      - ./npm/data:/data
      - ./npm/letsencrypt:/etc/letsencrypt
    depends_on:
      - app
      - pma
    networks:
      - spring_network
      - npm-network
  mariadb:
    image: mariadb:11.4
    container_name: mariadb_db
    restart: unless-stopped
    environment:
      MARIADB_ROOT_PASSWORD: ${MARIADB_ROOT_PASSWORD}
      MARIADB_DATABASE: ${MARIADB_DATABASE}
      MARIADB_USER: ${MARIADB_USER}
      MARIADB_PASSWORD: ${MARIADB_PASSWORD}
    volumes:
      - ./mariadb_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "healthcheck.sh", "--connect", "--innodb_initialized"]
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - spring_network

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: spring_app
    restart: unless-stopped
    environment:
      SPRING_DATASOURCE_URL: jdbc:mariadb://mariadb:3306/${MARIADB_DATABASE}?createDatabaseIfNotExist=true
      SPRING_DATASOURCE_USERNAME: ${MARIADB_USER}
      SPRING_DATASOURCE_PASSWORD: ${MARIADB_PASSWORD}
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
      CORS_ALLOWED_ORIGINS: ${CORS_ALLOWED_ORIGINS}
      SPRING_WEB_RESOURCES_STATIC_LOCATIONS: file:/app/static/
      SPRING_THYMELEAF_PREFIX: file:/app/templates/
    volumes:
      - ./src/main/resources/static:/app/static
      - ./src/main/resources/templates:/app/templates
    depends_on:
      mariadb:
        condition: service_healthy
    networks:
      - spring_network

  pma:
    image: phpmyadmin/phpmyadmin:latest
    container_name: phpmyadmin
    restart: unless-stopped
    environment:
      PMA_HOST: mariadb
      PMA_PORT: 3306
      MYSQL_ROOT_PASSWORD: ${MARIADB_ROOT_PASSWORD}
      UPLOAD_LIMIT: 256M
      PMA_ABSOLUTE_URI: https://pma.jvm.ee
    depends_on:
      - mariadb
    networks:
      - spring_network

networks:
  spring_network:
  npm-network:
    external: true
